### ISSUE TITLE
Feature request: allow the teacher to be notified of new uploads

### ISSUE THREAD

**Issue by frankiekam** [academic-moodle-cooperation/moodle-mod_publication#21]
As a teacher using the Student Folder plugin, I have to check the activity on a regular basis if I wanted to approve file uploads. Not every student who uploads a file will alert me by Email. What is needed is to automate the process of file upload notification. It would be more convenient if the teacher were to receive a notification each time a file is uploaded. For now, the plugin only logs these two events which can be selected from Event selection list of Moodle's event monitoring rule settings (see the screenshot at http://www.moodurian.com/tornado/images/event-monitoring-student-folder.jpg): 
"Course module instance list viewed" and 
"Course module viewed".  
My suggestion for improvement is for the plugin to also log the event of a file upload, which would result in a third event named "File uploaded" being listed in the Event selection list.

**Comment by kaspot** [comment]
Thanks Frankie for this idea and the suggestions you provided. I added this feature request to our tracking system to consider it for 3.4.

**Comment by chstdu** [comment]
We are using the student folder module for Moodle in our recent seminar course. It would be nice if there was the possibility to get (teacher's) notifications when students uploaded documents.  However, it would be even greater if there also was the possibility to notify the students whenever a document is approved and published by us.

We are using the module to collect handouts and presentation slides from the students and would appreciate such a notification option for the students so that we do not have to remind them to read the documents whenever there is a new one published.

**Comment by kaspot** [comment]
Hi, 
thanks for this idea - we will consider it together with the messages for teachers.

**Comment by goggo24** [comment]
Hey, good news - notifications for teachers (upload from documents) and for students (change of approval ) will be included in v.3.7.0. - coming soon! Cheers, Eva
