### ISSUE TITLE
Feature Request: add a Moodle internal view of the files

### ISSUE THREAD

**Issue by Kathrin84** [academic-moodle-cooperation/moodle-mod_publication#4]
Hi,

at the moment with your plugin it is only possible to download the files stored in the folder as a zip archive. 
It would be great, especially for those users accessing Moodle with their mobile devices if you could provide the possibility to directly view the files within Moodle. Accessing files on a mobile device via a zip archive might be really tricky.

Kind regards
Kathrin

**Comment by mkemmerling** [comment]
Hi Kathrin,

thank you for bringing this up. I forwarded your feature request to our developers to see if it can be implemented in the next version of the plugin.

**Comment by Kathrin84** [comment]
Hi, 
as it's been some time since I brought up this issue, I just wanted to ask if there's a chance that this feature might get implemented. We would really like to use this plugin. However, an internal displaying option is mandatory for our system.
Greetz

**Comment by mkemmerling** [comment]
Hi Kathrin,
we haven't decided upon your request yet. The developer is currently updating the plugin for Moodle 2.9. But the request is in our backlog, so the chance is certainly alive. If it helps your planning: If we decide to implement the feature, it will be available about February/March 2016 for Moodle 2.9 and 3.0.

**Comment by kaspot** [comment]
Hi Kathrin, can you help us to clarify this issue please. Aren't you able to see any files on your mobile device - so even the separate uploaded files in the student folder overview table?
And if that's the case, are you able to see and open e.g. assignment uploads from students?

**Comment by Kathrin84** [comment]
I can see the list of files and my personal device is also able to unzip a zip-archive. However with the iPad it is more tricky as I have to choose an app to open the archive with. At the moment I don't have a suitable app on that device. That was only an additional thought for providing an internal view / preview of the file.

Generally, it would be nice if the contents of the files could be watched within Moodle without the need to download them. So the user gets the content without the need to switch from the browser to another software / app. This is surely not quite productive. Do you know what I mean and want to tell you? :)

**Comment by kaspot** [comment]
Hi Kathrin, thanks for the additional information. Just to be sure - how does this behaviour occur within the Moodle standard assignment module? We just want to compare the functionality.

**Comment by Kathrin84** [comment]
Hi, the assignment and the folder behaves as your plugin does. Nevertheless it would be great if a kind of view / preview function without the need to download the ressource could be implemented. :)

**Comment by Kathrin84** [comment]
When viewing the header attributes of a file, there's Content-Disposition attachment set. This forces the browser to show up a save as dialog and this might be contraproductive for some operating systems or file types.
Just an info. :)

**Comment by kaspot** [comment]
Hi Kathrin, thanks for the details and your feedback. So at least it behaves like moodle standard modules do - which doesn't mean that it's always the best way :-)
But I still don't get what kind of preview you would like to have. Is there some other place in moodle where you could "show" me what you would like to have. 
Because I assume that the preview in the table view is not sufficient for you, right?

**Comment by abias** [comment]
Hi Kasia,

I'd like to chime in here and explain the situation from my point of view.

The functionality of your plugin is fine (thanks again!) for Desktop use. Students are able to upload files to the folder and download them to their computer. 

When I download a single file in your activity, it serves (just like the Moodle core activitiy mod_folder does) this file with a "Content-Disposition:attachment" HTTP header which forces a webbrowser to save the file to disk instead of display it within the browser window. This is probably done for security reasons, but does not make much sense for media which could be displayed directly in the browser like images or PDFs.

On mobile devices which might not have a file system as we use to know it from Desktops, this behavior can produce real problems because the mobile device might not be able to do a download as we use to know it or ask the user to save the download into some other app which might be registered to handle the mimetype of the file to be downloaded which is not what the user wants to do. In the end, user's might be unable to view a simple PDF or image from the student folder on a mobile device because of this technical reason and will contact the support staff.

The other problem of mobile devices is the fact that some of them might not be able to do a upload as we use to know it to your activity, but there's nothing you can do about it in your plugin.

I know that it might be hard to simply switch off the "Content-Disposition:attachment" header because there are reasons to keep it. Perhaps it does not come from your plugin at all but from Moodle core because you are using some API call.

But I hope that I could at least shed some light on the problem we are facing.
However, I am not angry if you want to keep the status quo. In this case, just close the ticket and you're done.

Thanks,
Alex

**Comment by mkemmerling** [comment]
Hi Alex,

I don't get what you are saying. I have little experience with Android, but Safari on iOS simply ignores the "Content-Disposition:attachment" header. Since there is no user accessible file system you need to have an app installed that is able to handle the content. Images and PDFs are opened in mobile Safari itself. A ZIP file may be stored e.g. in your Dropbox – if you have the Dropbox app on your iOS device. If you don't have an app that can handle ZIP files it doesn't make any sense to download it on iOS.

BTW: We have a central repository for learning resources at our university with hundreds and thousands of files (including ZIP files) that are served with the "Content-Disposition:attachment" header and never got any complaint from students of not being able to view them on a mobile device.

So I am closing this ticket. If you still feel there is a problem please open a new ticket with more precise information.

**Comment by frankiekam** [comment]
@Kathrin84 Something like this? http://moodurian.blogspot.co.uk/2015/11/view-pdf-files-in-pop-up-window-in.html
At the moment it only works with PDF files that are dragged-and-dropped into the course page. Other files get downloaded the usual way. I can try my hand at getting the Student Uploads mod to open a PDF window (as per my hack in the blog post) when you click on a PDF file listed in the uploads listing. It involves a code hack since I'm a total newbie to Moodle mod development. Haha.
