### ISSUE TITLE
Approved by default not working

### ISSUE THREAD

**Issue by behoof** [academic-moodle-cooperation/moodle-mod_publication#45]
L.s.

Using moodle v3.8.1 with Student Folder version 2020010501.

**Global Settings:**
- Obtain approval: No
- Approved by Default: Yes
- Sync automatically: Yes.

**Settings Student Folder:**
- Obtain Approval: Yes

**Expected behaviour**:
- All uploaded files are visible to other students.

**Expected behaviour**:
- The document are not visible to other students unless students manually approve.

Best regards,

Bert

**Comment by goggo24** [comment]
Thanks for reporting - we will have a look.

**Comment by goggo24** [comment]
We just tried to reproduce the bug with our newest version, but there it works fine. 

As we tried to reproduce it, we are not sure if you mixed up the two modes - what do you mean with global and student folder setting? The settings as you described them, don't appear together.
@students can upload documents - Approved by default: Yes => means all files are visible to all students 
@take documents from an assignment - Obtain Approval: Yes => means that students have to approve, so that everybody can see her/his file. if you choose no, than you as a teacher instead can give the approval and files will get visible to everybod - please note that this is work by students and that they should have given their agreement for publishing it!

See also https://www.academic-moodle-cooperation.org/fileadmin/user_upload/p_aec/Cheat_Sheets/Use_the_student_folder-EN.pdf

**Comment by goggo24** [comment]
@behoof any questions? Otherwise I would close this issue.
