### ISSUE TITLE
Feature: Student folder should allow automatic activity completion upon submission or other conditions

### ISSUE THREAD

**Issue by jmr-ua-pt** [academic-moodle-cooperation/moodle-mod_publication#76]
This is a feature request.

It should be possible to set student folder to automatically mark activity completion conditionally on file submission, for example.
This is essential if one needs to reliably restrict other activities until submission is complete.

Assignments and other activities in Moodle already have this setting available.

**Comment by goggo24** [comment]
Which version of the plugin do you use? The acitivity completion was added from v.4.2.x. 

In mode "Upload files directly in the current activity" the view of the activity as well as the upload of a file can be choosen. 
![image](https://github.com/academic-moodle-cooperation/moodle-mod_publication/assets/16721900/6cb5acc8-92f2-4bca-8bf1-f7e144c99405)

In mode " Import files from an assignment activity" only view was implemented, because the files are synchronised from an assignment activity.

Is this the function you were looking for? Eva

**Comment by goggo24** [comment]
So I will close this issue ;)
